### ISSUE TITLE
updateBricks() call should have a generic interface for the parameter

### ISSUE THREAD

**Issue by kenyee** [wayfair/brickkit-android#113]
Doesn't look like there's a reason it needs to be a LinkedList.

https://discuss.kotlinlang.org/t/why-kotlin-does-not-provide-linkedlist-implementation/15991/6

Kotlin doesn't have LinkedLists.

get() can't be efficient on a linkedlist...

https://github.com/wayfair/brickkit-android/blob/8b83b570cddf7aa6dc023b5e0c933639e7fdd6cd/BrickKit/bricks/src/main/java/com/wayfair/brickkit/BrickDiffUtilCallback.java

**Comment by mdemaso** [comment]
Hey Ken! Hope things are going well!

I agree that the DiffUtil can probably be moved to a List or some other "easier to access via an index" structure. I would however caution that the LinkListed is used inside the [BrickDataManager](https://github.com/wayfair/brickkit-android/blob/8b83b570cddf7aa6dc023b5e0c933639e7fdd6cd/BrickKit/bricks/src/main/java/com/wayfair/brickkit/BrickDataManager.java) as a source of truth. It does make adding things before and after other elements in the middle of the list efficient and clean. Also, the functionality for traversing forward and backwards across the data set is used heavily in the calculation of the margin and padding of each brick in [computePaddingPosition(BaseBrick currentBrick)](https://github.com/wayfair/brickkit-android/blob/8b83b570cddf7aa6dc023b5e0c933639e7fdd6cd/BrickKit/bricks/src/main/java/com/wayfair/brickkit/BrickDataManager.java#L924).

If this change is made, I'd worry about synchronising the data in the two forms as it currently just passes a reference to the same LinkedList the DataManager uses for the display of the items.

**Comment by kenyee** [comment]
Ugh...thanks for the insight 😞 

Hope things are going well for you too 😄
