### ISSUE TITLE
Inconsistent between notify functions and dataManger.getRecyclerViewItems().get(position)

### ISSUE THREAD

**Issue by jingweihu** [wayfair/brickkit-android#81]
We wrap all the adapter dataSetChanged changes with handle, which will post those events to the messageQueue asynchronously, but the items in the dataManager have been changed immediately.  In certain case, items might still exist in the recycler adapter but have been removed/moved in the datamanager item lists.

**Comment by thusson13** [comment]
Cannot reproduce
